---
title: "Manifesting a New Direction"
subtitle: "Reflections of an aspiring data scientist, four weeks into a data science bootcamp at Flatiron School"
author: "Rebecca Frost-Brewer"
date: '2022-03-19'
slug: []
categories: []
tags: []
output: html_document
---

The pandemic effect and manifesting a new direction.

After six years working in higher education administration and the successful completion of a Master's degree in Political Science, I am changing careers into data science and analytics. 

As I reflect back on my professional life to date, it's characterized by a lack of intentionality, a lack of purpose. I was glad to be employed and didn't think to consider what else or what more could be possible or achievable. As a result, I found myself underemployed, underutilized, and frankly, bored. The Covid-19 pandemic highlighted the discrepancies between what I wanted and what I had, so I decided to make a change.

While I completed a Master's in Political Science over the course of May 2020 - December 2021, I found myself using R - the first coding or programming language I'd ever encountered - for my classwork, from quantitative analyses to data visualizations and shiny apps (for some examples of my work, check out [the projects](https://www.frostbrewer.com/project/) section of my website. Using and working within R, experiencing just the tip of the tip of the iceberg about this whole world of data science and analytics, I was hooked. I needed and wanted more. 

Using R to clean and explore data, to analyze data, and to visualize data, I saw a whole new world of possibility open before me. So, I started looking into what sorts of jobs exist out there in this world. I began saving job postings and job descriptions, keeping track of what interested me in terms of scope as well as what experience and proficiencies will be necessary, listed below.


### Job responsibilities:

* You will help build some of the largest and most innovative research data products in the world
* Collect data from survey instruments, APIs, and relational databases
* Assess the effectiveness and accuracy of new data sources and data gathering techniques
* Deploy statistical models with a focus on accuracy, speed, and efficiency
* Develop and deploy processes and tools to monitor and analyze pipeline performance and data accuracy
* Compile and analyze trend questions and data 
* Develop key research questions 
* Conduct advanced analyses of survey datasets and other data sources 
* Prepare tables and charts 

### Skill and proficiencies:

* Experience with survey data – weighting, questionnaire design, etc.Experience with relational databases such as PostgreSQL 
* Experience using Python and SQL; R helpful as well
* Experience using tools such as Pandas to manipulate data and draw insights from datasets rapidly
* Strong quantitative skills, including an ability to use statistical programs or packages (e.g., SPSS, R, Stata) to organize and analyze large amounts of data 

### Soft skills:

* Motivated to contribute independently on tough research problems 
* Skilled at communicating results and research methodology though reports (R Markdown, Shiny, data visualization with ggplot)
* Ability to digest and communicate statistical information to nontechnical stakeholders
* Strong project management, attention to detail, and written and oral communication skills
* Resourceful
* You deal well with open ended problems (i.e., figuring out the right questions to ask about a dataset) rather than being told exactly what to analyze or how to analyze it
* You consider yourself to be an excellent “data wrangler”
* A drive to learn and master new technologies and techniques

***

As I discovered that these jobs exist out there, in the industries and spaces that I am interested in, I began to realize that perhaps I could have more out of my career than I had previously thought possible. Perhaps I could find a job that invigorated me, that challenged me, and that leveraged my abilities, skills, and strengths. I started asking myself: **What are my "zone of genius" interest areas?** What are those tasks or problems that activate and exhilarate me?

Throughout my Master's program in Political Science, I wondered about the effect of morally convicted political attitudes and ideological polarization on political behavior and what potential ramifications may exist for the future and stability of our democracy (see further reading below). From these articles and my own thesis research, initial questions brought up more questions. Are moral political attitudes becoming a cleavage further dividing Americans, and to what effect? Are morality and culture being used as a political weapon, and with what consequences? Further, what data exists to measure ideology, polarization, and morality? Are we seeking and utilizing data from sources that are innovative and not yet mined?

While these questions may be better suited for political scientists, data science is at the core; data science is about "infrastructure, testing, machine learning for decision making, and data products" ([Bowne-Anderson](https://hbr.org/2018/08/what-data-scientists-really-do-according-to-35-data-scientists)). Data scientist Jacqueline Nolis breaks data science down into [three components](https://hbr.org/2018/08/what-data-scientists-really-do-according-to-35-data-scientists):

1. Business intelligence, which is essentially about “taking data that the company has and getting it in front of the right people” in the form of dashboards, reports, and email (or perhaps, political intelligence, data the government has, or advocacy groups, or lobbying groups, and getting that data into a readable, digestible format for constituents, voters, or the public)
2. Decision science, which is about “taking data and using it to help a company make a decision” (or helping the government or department make a decision)
3. Machine learning, which is about “how can we take data science models and put them continuously into production” (for example, with political polling, public opinion, etc.)

***

I enrolled with Flatiron School to kickstart this journey to become a data scientist, to examine what questions need answering and to find and present the related data necessary to provide answers because I am confident I have the **high-powered skills** necessary to be successful, both from my previous educational and professional experience and from the technical training I am receiving through Flatiron's bootcamp. At the conclusion of Phase 1 of the data science bootcamp, I gained experience using `bash` and `git`; I conducted exploratory data analysis and visualization using base Python and `pandas`; I conducted database queries using SQLite and tried my hand at NoSQL using MongoDB; and I accessed data using an API for the first time!

This online space is where I will continue to show my learning and progress as I continue on this journey to becoming a data scientist.

***


**Further Reading**

* [The Origins and Consequences of Affective Polarization in the United States](https://www.annualreviews.org/doi/abs/10.1146/annurev-polisci-051117-073034)
* [The Moral Roots of Partisan Division: How Moral Conviction Heightens Affective Polarization](https://www.cambridge.org/core/journals/british-journal-of-political-science/article/abs/moral-roots-of-partisan-division-how-moral-conviction-heightens-affective-polarization/78B6152EF1CBD7D8890DC0D48B6D65B4)
* [Ideologues without Issues: The Polarizing Consequences of Ideological Identities](https://academic.oup.com/poq/article/82/S1/866/4951269?login=true)
